### ISSUE TITLE
Sync is no longer working as of today

### ISSUE THREAD

**Issue by mathisgauthey** [atymic/todo-sync#38]
Hi there, yesterday everything was working fine with this amazing project. But today, my reminders are staying on Google side and not being transferred to Todoist. I don't know if it's something on your end, but it was working fine until yesterday evening.

Thanks in advance !

**Comment by atymic** [comment]
Hi @mathisgauthey can you check again?

**Comment by mathisgauthey** [comment]
Hey, I don't know what you did, but I tried and saw the software at work on my calendar:
- Created a Google reminder with assistant.
- Soft created a todoist task.
- Soft deleted the Google reminder.

Everything is fine now, thanks you, it's amazing work especially considering the new assistant V2 on IFTTT which doesn't allow that kind of thing anymore!
