### ISSUE TITLE
Syncing seems to be broken

### ISSUE THREAD

**Issue by micklynch** [atymic/todo-sync#42]
I've been using this app for a while -- awesome work btw!

Today I noticed it's stopped syncing. I'm using your freely hosted version on https://todo-sync.atymic.dev/. I was able to log in and everything looks normal through the UI. 

When I create a reminder on Google, it doesn't sync with Todoist.

**Comment by atymic** [comment]
Should be resolved now :)
Todoist changed their API so syncs were failing.

You may have to login and re-enable sync.

**Comment by micklynch** [comment]
Awesome, can confirm fix! Thanks so much 👍
